image: freebsd/latest
sources:
  - https://git.sr.ht/~cdo/phal
tasks:
  - setup: |
      curl -sSf https://sh.rustup.rs | sh -s -- -y
  - build: |
      source $HOME/.cargo/env
      cd phal
      cargo build
  - test: |
      source $HOME/.cargo/env
      cd phal
      cargo test
