[package]
name = "phal"
description = "Pokes Hardware And Listens"
version = "0.1.0"
authors = ["Callum David O'Brien <cdo@teknik.io>"]
edition = "2018"

[dependencies]
xu4-hal = "0.1.1"
embedded-hal = { version = "0.2.3", features = [ "unproven" ] }
rocket = { version = "0.4.2", default-features = false }
