[package]
name = "phal"
description = "Pokes Hardware And Listens"
version = "0.1.0"
authors = ["Callum David O'Brien <cdo@teknik.io>"]
edition = "2018"

[dependencies]
gpio-cdev = "0.2.0"
rocket = { version = "0.4.2", default-features = false }
